# .github/workflows/deploy.yml

name: Deploy Flutter Web to GitHub Pages

on:
  # Trigger the workflow every time you push to the `master` branch
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push to the gh-pages branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      # New step to create the secrets.dart file
      - name: Create secrets file
        run: |
          echo "const String geminiApiKey = '${{ secrets.GEMINI_API_KEY }}';" > lib/secrets.dart
        
      - name: Install dependencies
        run: flutter pub get

      - name: Build web application
        run: flutter build web --base-href /vivechat/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web